[package]
name = "afrim-js"
version = "0.1.0"
authors = ["Brady Fomegne <fomegnemeudje@outlook.com>"]
edition = "2018"
description = "Afrim engine for javascript."
repository = "https://github.com/pythonbrad/afrim-js"
license = "MIT"
keywords = ["rust", "afrim", "wasm", "ime"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["strsim"]
strsim = ["afrim-translator/strsim"]

[dependencies]
wasm-bindgen = "0.2.84"
afrim-preprocessor = { version = "0.5.0", default-features = false }
serde-wasm-bindgen = "0.6.1"
afrim-translator = { version = "0.0.2", default-features = false }
indexmap = { version = "2.0.2", features = ["serde"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
