[package]
name = "afrim"
version = "0.5.0"
authors = ["Brady Fomegne <fomegnemeudje@outlook.com>"]
edition = "2018"
description = "Afrim engine for javascript."
repository = "https://github.com/pythonbrad/afrim-js"
license = "MIT"
keywords = ["rust", "ime", "keyboard"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["rhai", "strsim"]
strsim = ["afrim-translator/strsim"]
rhai = ["afrim-translator/rhai-wasm"]

[dependencies]
wasm-bindgen = "0.2.126"
afrim-preprocessor = { version = "0.7.0", default-features = false, features = ["serde"] }
serde-wasm-bindgen = "0.6.5"
afrim-translator = { version = "0.2.4", default-features = false, features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
toml = "1.1.3"

[dev-dependencies]
wasm-bindgen-test = "0.3.76"

[profile.release]
lto = "fat"         # turn on Link-Time Optimizations
codegen-units = 1   # trade compile time with maximum optimization
opt-level = "z"     # optimize for size
