name: CI

on:
  workflow_dispatch:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Fmt
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings


      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Test
        run: |
          cargo test --all-features
          wasm-pack test --headless --firefox

      - name: Wasm Build
        run: |
          wasm-pack build --release

